.TH CURLFISH 1
.SH NAME
curlfish \- notify user if a script has DOS-style line endings
.SH SYNOPSIS
.B curlfish
[\fB\-h\fR] [script] [optional script parameters ignored]
.SH DESCRIPTION
.B curlfish
prints a message indicating either that the invoking script has CRLF line endings or that 
.IR "this is not the shell you are looking for".
.SH OPTIONS
.TP
.BR \-h 
Display a usage message
